services:
  command_service:
    build: springboot_cqrs_command/.
    container_name: springboot_cqrs_command
    ports:
    - 8181:8080
    networks:
      - frontend
      - backend

  query_service:
    build: springboot_cqrs_query/.
    container_name: springboot_cqrs_query
    ports:
      - 8182:8081
    networks:
      - frontend
      - backend

  frontend_service:
    build: react_mui_cqrs/.
    container_name: react_mui_cqrs
    ports:
    - 8183:5173
    networks:
      - frontend

networks:
  frontend:
    external: false
  backend:
    external: false