resource "null_resource" "write_env" {
  provisioner "local-exec" {
    command = <<EOT
cat > ${var.working_directory}/.env <<'EOF'
# Generated by Terraform
# Command to regenerate: terraform apply -target=null_resource.write_env -auto-approve

DB_URL="${format("jdbc:postgresql://%s/%s", aws_db_instance.web_db.endpoint, var.db_schema)}"
DB_USERNAME="${var.db_username}"
DB_PASSWORD="${var.db_password}"
JWT_SECRET="${var.jwt_secret}"

VITE_HOST_IP="${aws_instance.web_server.public_ip}"
VITE_COMMAND_PORT="${var.command_service_port}"
VITE_QUERY_PORT="${var.query_service_port}"
EOF
EOT
  }

  triggers = {
    db_endpoint  = aws_db_instance.web_db.endpoint
    db_schema    = var.db_schema
    db_user      = var.db_username
    web_ip       = aws_instance.web_server.public_ip
    command_port = var.command_service_port
    query_port   = var.query_service_port
  }
}