name: Build and Push Docker Image
on:
  push:
    branches:
    - main
    - develop
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build-and-test:
    environment: "AWS and Supabase"
    name: Build and Test CQRS Application
    runs-on: ubuntu-latest
    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ vars.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: build Command Unit
        run: |
          chmod +x mvnw
          ./mvnw 
          ./mvnw clean package -DskipTests
        working-directory: springboot_cqrs_command

      - name: Build Query Unit 
        run: |
            chmod +x mvnw
            ./mvnw clean package -DskipTests
        working-directory: springboot_cqrs_query

      - name: Start All Services
        run: |
          docker compose -f docker/compose.yaml -f docker/docker-compose.override.yaml build --no-cache
          docker compose -f docker/compose.yaml -f docker/docker-compose.override.yaml up -d

      - name: Verify services are running
        run: docker ps

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker compose -f docker/compose.yaml -f docker/docker-compose.prod.yaml push