name: Deploy Image to EC2 Instance

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    branches:
      - main
      - develop
    types:
      - completed
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  setup-terraform:
    environment: "AWS and Supabase"
    name: Set up AWS EC2 Instance with Terraform
    runs-on: ubuntu-latest
    steps:
        - name: print out context
          run: |
            echo "GITHUB_REF: ${{ github.ref }}"
            echo "GITHUB_SHA: ${{ github.ref_name }}"
            echo "GITHUB_WORKFLOW: ${{ github.base_ref }}"
            echo "GITHUB_EVENT_NAME: ${{ github.head_ref }}"
            echo "GITHUB_ACTOR: ${{ github.workflow }}"