name: Build and Test CQRS Application

on:

  push:
    branches:
    - main
    - develop
  workflow_dispatch:

jobs:
  test-deployment:
    name: Build and Test CQRS Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Set up DB
        run: |
          docker compose up postgres -d --build
          until docker exec postgres-cqrs-db pg_isready; do
            sleep 2
            done
          echo "PostgreSQL is ready!"
      
      - name: build Command Unit
        run: |
          chmod +x mvnw
          ./mvnw flyway:migrate
          ./mvnw clean package -DskipTests
        working-directory: springboot_cqrs_command

      - name: Build Query Unit
        run: |
          chmod +x mvnw
          ./mvnw clean package -DskipTests
        working-directory: springboot_cqrs_query

      - name: Start All Services
        run: |
          docker compose build --no-cache
          docker compose up -d

      - name: Verify services are running
        run: docker ps